//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeClubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terrain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terrain()
        {
            this.EntrainementClubTerrain = new HashSet<EntrainementClubTerrain>();
            this.MatchsClubTerrain = new HashSet<MatchsClubTerrain>();
        }
    
        public int id { get; set; }
        public string adresse { get; set; }
        public int id_Club { get; set; }
        public string nom { get; set; }
    
        public virtual Club Club { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntrainementClubTerrain> EntrainementClubTerrain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchsClubTerrain> MatchsClubTerrain { get; set; }
    }
}
